# Generated by Django 4.2.2 on 2023-06-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_order_receipt_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='product_preview_directory_path'),
        ),
    ]
